Repository prow-clarketm/prow, pull requests merged in 2019-09, with the labels that each got.

#33 Do not replace configmaps
  starter_after.yaml
Labels: approved, size/M

#32 Create test.txt
  test.txt
Labels: ok-to-test, size/XS

#31 Add branch protection
  Makefile
  config.yaml
Labels: approved, size/L

#30 Format yaml
  starter_after.yaml
Labels: approved, size/XL

#34 Fail test and cronjob
  config.yaml
  starter_after.yaml
Labels: approved, size/M

#35 Create example.txt
  example.txt
Labels: size/XS
